#!/bin/sh
#
#          ██          ██   ██
#         ░░          ░░   ░██
#  ██   ██ ██ ███████  ██ ██████ ██████  █████
# ░░██ ██ ░██░░██░░░██░██░░░██░ ░░██░░█ ██░░░██
#  ░░███  ░██ ░██  ░██░██  ░██   ░██ ░ ░██  ░░
#   ██░██ ░██ ░██  ░██░██  ░██   ░██   ░██   ██
#  ██ ░░██░██ ███  ░██░██  ░░██ ░███   ░░█████
# ░░   ░░ ░░ ░░░   ░░ ░░    ░░  ░░░     ░░░░░
#
# ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
# ░▓ author: Theodosios Dimitrasopoulos Novak | theonovak@mailfence.com ▓
# ░▓   info: https://linktr.ee/theo_dmtr                                ▓
# ░▓   repo: https://github.com/theo-dim/dotfiles-deluxe                ▓
# ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
#
# merge custom x resources
xrdb -merge ~/.Xdefaults &

# fix + autohide cursor
xsetroot -cursor_name left_ptr &
unclutter &

# gestures
libinput-gestures-setup start &

# hotkeys
sxhkd &

# notifcations
dunst &

# wm
~/bin/display &
~/bin/clock &
~/bin/tray &
exec windowchef -c ~/.config/windowchef/windowchefrc
exec startplasma-x11
export DESKTOP_SESSION=plasma
